# a=(1,'aman',2,'rahul')
# print(len(a))
# print(a)
# print(type(a))
# print(a[1])
# print(a[-1])
# # del(a)
# print(a)
# q,*w,e=a
# print(q)
# print(w)
# print(e)
tuple1 = ('a', 'b', 'c', 'd', 'e')
tuple2 = ('1','2','3')
tuple3 = ('a', 'b', 'c', 'd', 'e')
print(tuple1)
print(tuple2)
print(tuple3)
print(len(tuple1))
print(len(tuple2))
print(len(tuple3))

print(min(tuple1))
print(min(tuple2))
print(min(tuple3))
print(tuple1+tuple2)
